### PR TITLE
Enable Distributed FusedLAMB

### PR DESCRIPTION
**Pull request by athitten**
Enable distributed FusedLAMB in apex/contrib.

Command used to build:
python setup.py install --cpp_ext --cuda_ext --distributed_adam --xentropy --deprecated_fused_adam --distributed_lamb --fast_multihead_attn 2>&1 | tee ../apex_build_mha.log

### CODE REVIEW

**Comment by hubertlu-tw** [comment]
LGTM. Notice that there is no unit tests for distributed LAMB now in both upstream and ROCm fork. We may need to revisit its correctness in the future.

**Comment by hubertlu-tw** [comment]
There are three files changed compared to our master branch. 

Please also find the files changed compared to the [upstream](https://github.com/NVIDIA/apex) ([aa756ce](https://github.com/NVIDIA/apex/commit/aa756cec4359aff3df1d9abb68dc6e6e92920e0c)) as follows:
1. apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb.cpp (No difference)
2. apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb_kernel.cu (No difference)
3. apex/contrib/optimizers/distributed_fused_lamb.py ([diff_distributed_fused_lamb_py.txt](https://github.com/ROCmSoftwarePlatform/apex/files/7573142/diff_distributed_fused_lamb_py.txt))

**Comment by jithunnair-amd** [comment]
Hi @athitten, it looks like there are some more recent updates to distributed_fused_lamb.py in upstream, including adding more flags to `DistributedFusedLAMB` constructor. Do you want to bring in those updates as part of this PR or a separate one?

**Review by hubertlu-tw — APPROVED** [review]

**Comment by athitten** [comment]
> Hi @athitten, it looks like there are some more recent updates to distributed_fused_lamb.py in upstream, including adding more flags to `DistributedFusedLAMB` constructor. Do you want to bring in those updates as part of this PR or a separate one?

**Comment by athitten** [comment]
> Hi @athitten, it looks like there are some more recent updates to distributed_fused_lamb.py in upstream, including adding more flags to `DistributedFusedLAMB` constructor. Do you want to bring in those updates as part of this PR or a separate one?

@jithunnair-amd we plan to bring it in a separate one if need arises. At the moment we are just maintaining compatibility with MLPerf submission code. Let me know if you have any other questions.

**Pull request merged**
