### PR TITLE
pass all TensorListMetadata as pointer to pinned host memory

### PR DESCRIPTION
**Pull request by jeffdaily**
This works around a known performance issue.  When a real fix becomes available, we can revert this.

### CODE REVIEW

**Comment by lcskrishna** [comment]
Tested out locally for functional verification. 
@sunway513  Do you want to review it once.

**Comment by sunway513** [comment]
@lcskrishna , can you setup a CI run for the PR? Just for the interest to test our CI :-)

**Comment by lcskrishna** [comment]
Sure, i'll keep a CI run now.

**Comment by lcskrishna** [comment]
Passed all the tests : 
http://ml-ci.amd.com:21096/job/apex-rocm/18/console

**Pull request merged**
