### PR TITLE
Skip the unit tests

### PR DESCRIPTION
**Pull request by lcskrishna**
Skipping unit tests for stability of CI.

### CODE REVIEW

**Comment by lcskrishna** [comment]
jenkins: retest this please

**Comment by lcskrishna** [comment]
These are the unit tests that got regressed when using the latest ROCm versions. 
```
test_fuzz (Mulit-tensor-axpy)
test_fuzz (Multi_tensor_scale)
test_bfloat16( FUsedAdagrad)
test_float (FusedAdagrad)
test_multi_params (FusedAdagrad)
test_float (FusedAdam)
test_bfloat16 (FusedAdam)
```

**Comment by sunway513** [comment]
@lcskrishna can you confirm if the tests can pass using the public ROCm3.7 docker container?

**Comment by lcskrishna** [comment]
@sunway513 Public docker containers doesn't have hipify changes. With the hipify changes from pytorch installed on ROCm3.7 I don't see any issues locally.

**Comment by sunway513** [comment]
Thanks, that’s helpful.
LGTM, please go ahead merge it.

**Comment by lcskrishna** [comment]
Thanks!

**Pull request merged**
