### PR TITLE
Identify if hip-clang compiler is used while hipify

### PR DESCRIPTION
**Pull request by ashishfarmer**
This PR identifies if the compiler is hip-clang before hipifying APEX. There are some hip-clang specific source conversions which can be enabled with this flag passed to hipify(...) call

### CODE REVIEW

**Comment by jeffdaily** [comment]
I'm assuming `hip_clang_launch` is already a kwarg for hipify?

**Comment by jeffdaily** [comment]
Shouldn't this be pushed down into hipify itself, rather than asking callers of hipify to add this check?

**Comment by ashishfarmer** [comment]
It is a kwarg in hipify [call](https://github.com/pytorch/pytorch/blob/87f9b55aa58925f1ce80638d2031b584356a58e1/torch/utils/hipify/hipify_python.py#L824)
Pushing it to hipify is a better solution. I think it was left as is to experiment when we had hcc and hip-clang. I can try that on pytorch side and that will eliminate the need for this PR

**Comment by ashishfarmer** [comment]
The fix to add parenthesis around kernel name has landed on upstream. Will close this PR here and we will get the part done correctly in pytorch itself

**Pull request closed without merging**
