### PR TITLE
Enable mlp_cuda extension.

### PR DESCRIPTION
**Pull request by lcskrishna**
* This PR enables mlp_cuda extension.
* Enabled unit tests for mlp_cuda.

### CODE REVIEW

**Comment by lcskrishna** [comment]
jenkins: retest this please

**Comment by lcskrishna** [comment]
There is a timeout exception coming from the CI, 
```
docker: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/fc/fc82326769918b6e5bf985bf58d28c0f251bfa505de9ae2fb4408ed385a99197/data?verify=1595024299-kEjMx7sDFQrB0tzWGX8g%2FUOd%2B8o%3D: dial tcp: lookup production.cloudflare.docker.com on 8.8.8.8:53: read udp 172.16.190.131:49827->8.8.8.8:53: i/o timeout.
See 'docker run --help'.
```

**Comment by lcskrishna** [comment]
jenkins: retest this please

**Comment by lcskrishna** [comment]
jenkins: retest this please

**Comment by lcskrishna** [comment]
jenkins: retest this please

**Comment by ashishfarmer** [comment]
We might be hitting some accuracy issues here...

jenkins: retest this please

**Comment by sunway513** [comment]
Can we try if this test can pass in local tests?

**Comment by lcskrishna** [comment]
jenkins: retest this please

**Comment by lcskrishna** [comment]
jenkins: retest this please

**Comment by lcskrishna** [comment]
jenkins: retest this please

**Comment by lcskrishna** [comment]
Skipped the unit tests will be fixed in future releases.
cc: @ashishfarmer @sunway513

**Comment by lcskrishna** [comment]
CI passed, http://ml-ci.amd.com:21096/view/pytorch/job/pytorch/job/apex-rocm/68/console
Trying for second time.
jenkins: retest this please

**Comment by lcskrishna** [comment]
@ashishfarmer @jeffdaily @sunway513 Ready for reveiw.

**Comment by lcskrishna** [comment]
> Why are the `static_cast<long>` needed for HIP_PLATFORM only?

It throwed a compilation error to use the work_size as long and suggested to use static_cast<long>

**Comment by lcskrishna** [comment]
@jeffdaily Did I answer your question? or is there any other suggestions?

**Pull request merged**
