### PR TITLE
[FusedOptimizers] Bug fixes in fused optimizers for fp16/bfp16.

### PR DESCRIPTION
**Pull request by lcskrishna**
This PR is intended to enable the test suits : ```test_fused_sgd``` and ```test_multiple_models_optimizers_losses``` as mentioned in the the comment in the previous PR. 
https://github.com/ROCmSoftwarePlatform/apex/pull/5#issuecomment-629474681

### CODE REVIEW

**Comment by sunway513** [comment]
@rohithkrn can you help review? We need this been merged to unblock the CI progress.

**Comment by rohithkrn** [comment]
This looks like a typo from my previous PR. But, I am surprised if it makes difference to the logical flow of the program because if `grad_type == at::ScalarType::BFloat16` it would not enter any of the if branches above. I am curious to know what case fails without this change.

**Comment by lcskrishna** [comment]
@rohithkrn Yes, a simple logical flaw; after the calling the method with respect to fp16 tests, it tries to run if -> elseif->else condition again that has conditions for BFP16; where in the final else condition the error is thrown. 

```
RuntimeError: multi_tensor_sgd only supports some combinations of gradient & weight types. Given: gradient: Half, weight: Half, num_lists: 3

```

Tests failing are the same tests in your comment in your previous PR. These tests were passing before the introduction of BFloat16 PR. Attach this commit to verify: (65490af6af0e7b270a031cfe69f5cc612ffbc20c)

**Comment by lcskrishna** [comment]
CI Build passed with success: 
http://ml-ci.amd.com:21096/job/apex-rocm/19/console
```
test_2models2losses1optimizer (test_multiple_models_optimizers_losses.TestMultipleModelsOptimizersLosses) ... ok
test_2models2losses2optimizers (test_multiple_models_optimizers_losses.TestMultipleModelsOptimizersLosses) ... ok
test_3models2losses1optimizer (test_multiple_models_optimizers_losses.TestMultipleModelsOptimizersLosses) ... ok
test_3models2losses2optimizers (test_multiple_models_optimizers_losses.TestMultipleModelsOptimizersLosses) ... ok
....

test_2models2losses1optimizer (test_fused_sgd.TestMultipleModelsOptimizersLosses) ... ok
test_2models2losses2optimizers (test_fused_sgd.TestMultipleModelsOptimizersLosses) ... ok
test_3models2losses1optimizer (test_fused_sgd.TestMultipleModelsOptimizersLosses) ... ok
test_3models2losses2optimizers (test_fused_sgd.TestMultipleModelsOptimizersLosses) ... ok
```

**Comment by sunway513** [comment]
jenkins: retest this please

**Pull request merged**
